=== shicks255/dataStructures/src/main/resources/animalTreeSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="questionTree">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element name="node" type="nodeType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="nodeType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="left" minOccurs="0" maxOccurs="1" type="nodeType" />
            <xs:element name="right" minOccurs="0" maxOccurs="1" type="nodeType" />
        </xs:sequence>
        <xs:attribute name="data" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== shicks255/dataStructures/src/main/resources/animalTree.xml
<?xml version="1.0" encoding="UTF-8"?>

<questionTree xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="animalTreeSchema.xsd">
    <node data="Are you a mammal?" >
        <left data="Are you bigger than a cat?" >
            <left data="Kangaroo" />
            <right data="Mouse" />
        </left>
        <right data="Do you live underwater?" >
            <left data="Trout" />
            <right data="Robin" />
        </right>
    </node>
</questionTree>
